---

"COURSE": "CAU_OOP_2022"
"ASSIGNMENT": "ASSIGNMENT_03"

"ID": "00000000"
"FILES":
    - "cau_oop_2022/assignment_03/Vector3d.h"
    - "cau_oop_2022/assignment_03/Vector3d.cpp"    
"PROBLEMS": 
    - "PROBLEM_01"
    - "PROBLEM_02"
    - "PROBLEM_03"
    - "PROBLEM_04"
